---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: amaroun-os
description: Moje vlastní ublue Kinoite s hotovým msi-ec kmodem a NVIDIA ovladači.

base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: script
    scripts:
      - disable-multimedia.sh

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/xabi08/MSI-EC/repo/fedora-44/xabi08-MSI-EC-fedora-44.repo
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-44/atim-starship-fedora-44.repo
    install:
      # Explicitní synchronizace verzí přeruší zámek multilib konfliktu v obrazu
      - glibc.i686
      - glibc.x86_64
      - cpp
      # Vaše požadované balíčky
      - micro
      - starship
      - akmod-msi-ec
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.kde.gwenview
          - com.brave.Browser
          - com.valvesoftware.Steam
          - net.lutris.Lutris
      - scope: user

  - type: signing
