---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: amaroun-os
description: Moje vlastní ublue Kinoite s hotovým msi-ec kmodem a NVIDIA ovladači.

base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  # Přidán modul akmods, který sestaví msi-ec přímo proti správnému kernelu
  - type: akmods
    install:
      - msi-ec

  - type: rpm-ostree
    repos:
      # Odstraněn xabi08-MSI-EC repozitář, který způsoboval konflikt glibc/cpp
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-44/atim-starship-fedora-44.repo
    install:
      - micro
      - starship
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.kde.gwenview
          - com.brave.Browser
          - com.valvesoftware.Steam
          - net.lutris.Lutris
      - scope: user

  - type: signing
